1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 36, in <module>
    main()
  File "main.py", line 26, in main
    network.close()
  File "/home/pi/Hermes/raspi/network.py", line 105, in close
    client_socket.close()
AttributeError: 'NoneType' object has no attribute 'close'


2

^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
no detection
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
no detection
    elif lock.acquire(block, timeout):
KeyboardInterrupt
